apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  type: {{ .Values.service.dbType | default "ClusterIP" }}
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

