name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      #Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      #Deploy/Upgrade Helm chart
      - name: Deploy with Helm
        run: |
          helm upgrade --install todo ./todo-app-chart \
            --set app.image=${{ secrets.DOCKER_USERNAME }}/todo-app \
            --set app.tag=latest \
            --set db.password=${{ secrets.DB_PASSWORD }} \
            --namespace default


